name: apps
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  provider: ^2.0.0
  modern_charts: ^0.1.19
  image_picker: ^0.6.7+11
  flutter_speed_dial: ^1.2.1
  search_widget: ^1.0.2
  file_picker: ^1.9.0+1
  fl_chart: ^0.9.4
  font_awesome_flutter: ^8.8.1
  google_maps_flutter: any
  shared_preferences: ^0.5.7+3
  geolocator: ^6.0.0+3
  simple_animations: ^1.3.4
  flutter_local_notifications: ^0.8.4+3
  intl: ^0.16.1
  validate: ^1.7.0
  http: any
  flutter_datetime_picker: ^1.3.8
  convert: ^2.1.1
  charts_flutter: ^0.9.0
  json_table: ^1.4.0
  line_icons: ^0.2.0
  carousel_slider: ^1.3.1
  cached_network_image: ^2.3.1
  path_provider:
  liquid_progress_indicator: ^0.3.2
  flutter_signature_pad: ^2.0.2
  search_choices: ^1.0.17
  flutter_icons: ^1.1.0
  pull_to_refresh: ^1.6.1
  skeleton_text: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/sc1.jpg
    - assets/img/log.png
    - assets/img/agricultural.png
    - assets/img/portfolio.png
    - assets/img/addfund.png
    - assets/img/bell.png
    - assets/img/clipboard.png
    - assets/img/price-tag.png
    - assets/img/web-browser.png
    - assets/img/chat.png
    - assets/img/money.png
    - assets/img/farmer.png
    - assets/img/splash.jpg
    - assets/img/farming.gif
    - assets/img/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
